apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "1"
    helm.sh/hook: pre-install,pre-upgrade
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
