name: Deploy Dev

on:
  push:
    branches: [dev]

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      cluster-name: otus-test-cluster
    secrets: inherit