name: Deploy Prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      cluster-name: otus-test-cluster
    secrets: inherit